#!/bin/bash
# Script 1: System Identity Report
# Author: Yashasvi Sharma | Course: Open Source Software

# --- Variables ---
STUDENT_NAME="Yashasvi Sharma"
SOFTWARE_CHOICE="Linux System"

# --- System info ---
KERNEL=$(uname -r)
DISTRO=$(grep "^PRETTY_NAME" /etc/os-release | cut -d= -f2 | tr -d '"')
USER_NAME=$(whoami)
HOME_DIR=$HOME
UPTIME=$(uptime -p)
CURRENT_TIME=$(date)

# --- Display ---
echo "========================================"
echo "  Open Source Audit - $STUDENT_NAME"
echo "========================================"
echo "Distro     : $DISTRO"
echo "Kernel     : $KERNEL"
echo "User       : $USER_NAME"
echo "Home Dir   : $HOME_DIR"
echo "Uptime     : $UPTIME"
echo "Date/Time  : $CURRENT_TIME"
echo "========================================"
echo "License: Linux is distributed under the GNU General Public License (GPL)."
echo "========================================"
